import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to copy static files to dist
const copyStaticFiles = {
	name: 'copy-static-files',
	setup(build) {
		build.onEnd(() => {
			// Ensure dist exists
			if (!fs.existsSync('dist')) {
				fs.mkdirSync('dist');
			}

			// Copy static files
			if (fs.existsSync('styles/styles.css')) {
				fs.copyFileSync('styles/styles.css', 'dist/styles.css');
			}
			if (fs.existsSync('manifest.json')) {
				fs.copyFileSync('manifest.json', 'dist/manifest.json');
			}
			if (fs.existsSync('versions.json')) {
				fs.copyFileSync('versions.json', 'dist/versions.json');
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	plugins: [copyStaticFiles],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}