import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import fs from "fs";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to copy static files to dist
const copyStaticFiles = {
	name: 'copy-static-files',
	setup(build) {
		build.onEnd(() => {
			// Ensure dist exists
			if (!fs.existsSync('dist')) {
				fs.mkdirSync('dist');
			}

			// Copy static files
			if (fs.existsSync('styles/styles.css')) {
				fs.copyFileSync('styles/styles.css', 'dist/styles.css');
			}
			if (fs.existsSync('manifest.json')) {
				fs.copyFileSync('manifest.json', 'dist/manifest.json');
			}
			if (fs.existsSync('versions.json')) {
				fs.copyFileSync('versions.json', 'dist/versions.json');
			}
		});
	}
};

// First pass: bundle the encoding worker so its source can be inlined
// into the main bundle (the plugin starts it via a Blob URL). In watch
// mode the worker source is captured once at startup; restart the dev
// build after editing src/recording/encodingWorker.ts.
const workerBuild = await esbuild.build({
	entryPoints: ["src/recording/encodingWorker.ts"],
	bundle: true,
	format: "iife",
	target: "es2022",
	minify: prod,
	write: false,
});
const encodingWorkerSource = workerBuild.outputFiles[0].text;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: {
		__ENCODING_WORKER_SOURCE__: JSON.stringify(encodingWorkerSource),
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	// Obsidian desktop runs on a current Electron/Chromium; es2022
	// avoids transpiling class fields and top-level await helpers
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// Minified production bundle loads faster; the source stays
	// readable in this repository
	minify: prod,
	outfile: "dist/main.js",
	plugins: [copyStaticFiles],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}